### ISSUE TITLE
provide pretrained checkpoint

### ISSUE THREAD

**Issue by zakizhou** [brightmart/ai_law#2]
Can your provide the trained checkpoint to reconstruct your result?

**Comment by brightmart** [comment]
checkpoint may be several hundreds of M. where to save it
________________________________
发件人: Jie Zhou <notifications@github.com>
发送时间: 2018年6月22日 10:04:21
收件人: brightmart/ai_law
抄送: Subscribed
主题: [brightmart/ai_law] provide pretrained checkpoint (#2)


Can your provide the trained checkpoint to reconstruct your result?

―

**Comment by zakizhou** [comment]
@brightmart thank you for your reply, I think any cloud storage service is ok like Baidu pan, icloud, dropbox and etc.
