### ISSUE TITLE
AttributeError: 'EuclideanKeyedVectors' object has no attribute 'vectors'

### ISSUE THREAD

**Issue by tangdouer** [brightmart/ai_law#3]
('using pre-trained word emebedding.started.word2vec_model_path:', 'data/news_12g_baidubaike_20g_novel_90g_embedding_64.bin')
Traceback (most recent call last):
  File "/home/qiu/PycharmProjects/ai_law-master (2)/HAN_train.py", line 271, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/qiu/PycharmProjects/ai_law-master (2)/HAN_train.py", line 101, in main
    assign_pretrained_word_embedding(sess, vocabulary_index2word, vocab_size, model,FLAGS.word2vec_model_path,model.Embedding)
  File "/home/qiu/PycharmProjects/ai_law-master (2)/HAN_train.py", line 238, in assign_pretrained_word_embedding
    for word, vector in zip(word2vec_model.vocab, word2vec_model.vectors):
AttributeError: 'EuclideanKeyedVectors' object has no attribute 'vectors'

**Comment by brightmart** [comment]
did you follow readMe to download the pretrained word embedding as i mentioned?

**Comment by tangdouer** [comment]
Yes, I download the pretrained word embedding as you mentioned.

**Comment by brightmart** [comment]
I did not has this issue.


I am using python3 and this link  https://pan.baidu.com/s/1o7MWrnc for word embedding.


________________________________
发件人: tangdouer <notifications@github.com>
发送时间: 2018年6月26日 9:21
收件人: brightmart/ai_law
抄送: brightmart; Comment
主题: Re: [brightmart/ai_law] AttributeError: 'EuclideanKeyedVectors' object has no attribute 'vectors' (#3)


Yes, I download the pretrained word embedding as you mentioned.

―

**Comment by tangdouer** [comment]
Thank you very much.  This problem was solved when using python3
