### ISSUE TITLE
train and predictor

### ISSUE THREAD

**Issue by tangdouer** [brightmart/ai_law#4]
train:
tf.app.flags.DEFINE_string("ckpt_dir","./predictor/checkpoint/","checkpoint location for the model")
tf.app.flags.DEFINE_string("model","text_cnn","name of model:han,text_cnn,dp_cnn,c_gru,c_gru2,gru,pooling")
predictor:
tf.app.flags.DEFINE_string("model_dpcnn", "dp_cnn", "name of model:han,c_gru,c_gru2,gru,text_cnn")
tf.app.flags.DEFINE_string("ckpt_dir_dpcnn", "predictor/checkpoint_dpcnn_big32/", "checkpoint location for the model")

tf.app.flags.DEFINE_string("model", "text_cnn", "name of model:han,c_gru,c_gru2,gru,text_cnn")
tf.app.flags.DEFINE_string("ckpt_dir", "predictor/checkpoint/", "checkpoint location for the model")

当训练模型的时候是用text_cnn, 不理解在预测的时候为什么是用的text_cnn和dpcnn. 难道是在训练模型的时候，需要再训练dpcnn吗？谢谢您的帮助。

**Comment by brightmart** [comment]
there are several models available for you. if you train use text_cnn, during predict/test you also need to use text_cnn.


just by add parameter --model=text_cnn during predict/test


________________________________
发件人: tangdouer <notifications@github.com>
发送时间: 2018年6月27日 11:02
收件人: brightmart/ai_law
抄送: Subscribed
主题: [brightmart/ai_law] train and predictor (#4)


train:
tf.app.flags.DEFINE_string("ckpt_dir","./predictor/checkpoint/","checkpoint location for the model")
tf.app.flags.DEFINE_string("model","text_cnn","name of model:han,text_cnn,dp_cnn,c_gru,c_gru2,gru,pooling")
predictor:
tf.app.flags.DEFINE_string("model_dpcnn", "dp_cnn", "name of model:han,c_gru,c_gru2,gru,text_cnn")
tf.app.flags.DEFINE_string("ckpt_dir_dpcnn", "predictor/checkpoint_dpcnn_big32/", "checkpoint location for the model")

tf.app.flags.DEFINE_string("model", "text_cnn", "name of model:han,c_gru,c_gru2,gru,text_cnn")
tf.app.flags.DEFINE_string("ckpt_dir", "predictor/checkpoint/", "checkpoint location for the model")

当训练模型的时候是用text_cnn, 不理解在预测的时候为什么是用的text_cnn和dpcnn. 难道是在训练模型的时候，需要再训练dpcnn吗？谢谢您的帮助。

―

**Comment by tangdouer** [comment]
我使用命令  python main.py --model=text_cnn 还是会出现下面的错，请问应该怎么解决呀
Traceback (most recent call last):
  File "/home/qiu/PycharmProjects/ai_law-master (2)/main.py", line 8, in <module>
    predict=Predictor()
  File "/home/qiu/PycharmProjects/ai_law-master (2)/predictor/predictor.py", line 84, in __init__
    saver_big.restore(sess_big, tf.train.latest_checkpoint(FLAGS.ckpt_dir_dpcnn))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1796, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by tangdouer** [comment]
Thank you very much. This problem was solved.
