### ISSUE TITLE
你好，你在上传模型到比赛网站上遇到过这个错误吗？

### ISSUE THREAD

**Issue by jingyihiter** [brightmart/ai_law#5]
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 2982177973 vs. calculated on the restored bytes 1718988051
我上传之后总是这个问题，请问您有什么见解。
我在本地测试都不会出现问题，但是就出在上传会报这个错误。
为了验证是我代码的问题，还是上传出错。我今天把您的代码跑了一篇，然后在本地跑main.py正常，然后压缩上传了一次，同样出现了这种错误。我压缩的方式是zip -r -9 predictor.zip predictor/,我想既然我上传您的代码也会出现同样的错误，那错误应该不是出在代码里，而是压缩的步骤或上传的步骤中存在问题，请问您是怎么压缩文件上传的？

**Comment by tangdouer** [comment]
您好，您是使用什么命令运行作者的main.py文件的呢。

**Comment by jingyihiter** [comment]
@tangdouer python main.py 需要在本地训练之后，运行
————————
我用HAN_train.py 先训练的，模型保存在"predictor/checkpoint/"，然后修改了predictor.py里的内容，原本是模型融合的结果，我只训练了一个模型，所以改成了一个load一个模型。在本地运行main.py成功了

**Comment by tangdouer** [comment]
Traceback (most recent call last):
  File "/home/qiu/PycharmProjects/ai_law-master (2)/main.py", line 8, in <module>
    predict=Predictor()
  File "/home/qiu/PycharmProjects/ai_law-master (2)/predictor/predictor.py", line 84, in __init__
    saver_big.restore(sess_big, tf.train.latest_checkpoint(FLAGS.ckpt_dir_dpcnn))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1796, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.   那您有没有遇到这样的错误呢。

**Comment by jingyihiter** [comment]
@tangdouer 你看代码啊，predictor.py的84行里FLAGS.ckpt_dir_dpcnn这个模型的路径，你是否有啊！没有的话肯定Load出错。

**Comment by tangdouer** [comment]
那就是预测的时候要用到两个模型吗，text_cnn和dp_cnn?   谢谢您。

**Comment by brightmart** [comment]
是的。
