### ISSUE TITLE
how about your machine configure, and how to fix cpu 100% problem.

### ISSUE THREAD

**Issue by vincetom** [brightmart/ai_law#6]
great job! 
but when I use your code to train the 'big_data' (1700k),cpu always occupied 100%,then I cannot connect to my server.

**Comment by brightmart** [comment]
I am using 4 cpu(Intel Xeon E5-2682v4), 60g memory, 16g GPU( Nvidia-p100). 

you've better to use GPU as there are millions of training data & very long document, and cnn/rnn are computation expensive,。

for cloud gpu, please check:
https://www.aliyun.com/product/ecs/gpu
